enum item_type{
	pickup,
	weapon,
	armor,
	workbench,
	placeble,
}
enum armor_type{
	head,
	body,
	leggins,
	boots
}

global.Items = {
	Rock : {
		Name : "item_rock",
		Weight : 0.1,
		Item : ObRock,
		InvSprite : SpRock,
		Flags : [],
		Strength : false,
		Type : item_type.pickup,
	},
	Stick : {
		Name : "item_stick",
		Weight : 0.12,
		Item : ObStick,
		InvSprite : SpStick,
		Flags : [],
		Strength : false,
		Type : item_type.pickup,
	},
	Workbench : {
		Name : "item_workbench",
		Weight : 10,
		Item : ObWorkbench,
		InvSprite : SpWorkbench,
		Flags : [],
		Strength : false,
		Type : item_type.workbench,
	},
	StoneAxe : {
		Name : "item_stone_axe",
		Weight : 1,
		Item : ObStoneAxe,
		InvSprite : SpStoneAxe,
		Flags : [],
		Strength : true,
		StrengthMax : 15,
		StrengthCur : 15,
		Type : item_type.weapon,
	},
	StoneSword : {
		Name : "item_stone_sword",
		Weight : 1,
		Item : ObStoneSword,
		InvSprite : SpStoneSword,
		Flags : [],
		Strength : true,
		StrengthMax : 30,
		StrengthCur : 30,
		Type : item_type.weapon,
	},
	StonePickaxe : {
		Name : "item_stone_pickaxe",
		Weight : 1,
		Item : ObStonePickaxe,
		InvSprite : SpStonePickaxe,
		Flags : [],
		Strength : true,
		StrengthMax : 15,
		StrengthCur : 15,
		Type : item_type.weapon,
	},
	PegWool : {
		Name : "item_peg_wool",
		Weight : 0.01,
		Item : ObPegWool,
		InvSprite : SpPegWool,
		Flags : [],
		Strength : false,
		Type : item_type.pickup,
	},
	Log : {
		Name : "item_log",
		Weight : 1.2,
		Item : ObLog,
		InvSprite : SpLog,
		Flags : [],
		Strength : false,
		Type : item_type.pickup,
	},
	Bed : {
		Name : "item_bed",
		Weight : 4,
		Item : ObBed,
		InvSprite : SpBedMini,
		Flags : [],
		Strength : false,
		Type : item_type.placeble,
	},
}