enum flags{
	axe,
	sword,
	pickaxe,
	
	pickup,
	
	weapon,
	armor,
	
	workbench,
	
	placeble,
	
	head,
	body,
	leggins,
	boots,
	
	interactive,
	remeltable,
	food,
	fuel,
	
	recover,
}

enum food_stats{
	hp,
	mn,
	xp,
}

global.items = {
	rock : {
		Name : "item_rock",
		Weight : 0.1,
		Item : obj_rock,
		InvSprite : spr_rock,
		Flags : [flags.pickup],
	},
	stick : {
		Name : "item_stick",
		Weight : 0.12,
		Item : obj_stick,
		InvSprite : spr_stick,
		Flags : [flags.pickup, flags.remeltable, flags.fuel],
		Fuel : 1,
	},
	workbench : {
		Name : "item_workbench",
		Weight : 4,
		Item : obj_workbench,
		InvSprite : spr_workbench_icon,
		Flags : [flags.interactive, flags.workbench],
	},
	darkCreator : {
		Name : "item_dark_creator",
		Weight : 2,
		Item : obj_dark_creator,
		InvSprite : spr_dark_creator_icon,
		Flags : [flags.interactive, flags.workbench],
	},
	darkCreatorItem : {
		Name : "item_dark_creator",
		Weight : 2,
		Item : obj_dark_creator,
		InvSprite : spr_dark_creator_icon,
		Flags : [flags.pickup, flags.placeble],
		Replaceble : obj_dark_creator,
		ReplacebleSprite : spr_dark_creator,
	},
	workbenchItem : {
		Name : "item_workbench",
		Weight : 4,
		Item : obj_workbench_item,
		InvSprite : spr_workbench_icon,
		Flags : [flags.pickup, flags.placeble],
		Replaceble : obj_workbench,
		ReplacebleSprite : spr_workbench,
	},
	blockWoodItem : {
		Name : "item_block_wood",
		Weight : 1,
		Item : obj_block_wood_item,
		InvSprite : spr_block_wood_item,
		Flags : [flags.pickup, flags.placeble],
		Replaceble : obj_block_wood,
		ReplacebleSprite : spr_block_wood,
	},
	blockWoodDoorItem : {
		Name : "item_block_door",
		Weight : 1,
		Item : obj_block_wood_door_item,
		InvSprite : spr_block_wood_door_item,
		Flags : [flags.pickup, flags.placeble],
		Replaceble : obj_block_wood_door,
		ReplacebleSprite : spr_block_wood_door,
	},
	stoneAxe : {
		Name : "item_stone_axe",
		Weight : 1,
		Item : obj_stone_axe,
		InvSprite : spr_stone_axe,
		Flags : [flags.axe, flags.pickup, flags.weapon],
		Damage : 4,
	},
	stoneSword : {
		Name : "item_stone_sword",
		Weight : 1,
		Item : obj_stone_sword,
		InvSprite : spr_stone_sword,
		Flags : [flags.sword, flags.pickup, flags.weapon],
		Damage : 5,
	},
	stonePickaxe : {
		Name : "item_stone_pickaxe",
		Weight : 1,
		Item : obj_stone_pickaxe,
		InvSprite : spr_stone_pickaxe,
		Flags : [flags.pickaxe, flags.pickup, flags.weapon],
		Damage : 3,
	},
	pegWool : {
		Name : "item_peg_wool",
		Weight : 0.01,
		Item : obj_peg_wool,
		InvSprite : spr_peg_wool,
		Flags : [flags.pickup, flags.remeltable, flags.fuel],
		Fuel : 4,
	},
	log : {
		Name : "item_log",
		Weight : 0.2,
		Item : obj_log,
		InvSprite : spr_log,
		Flags : [flags.pickup, flags.remeltable, flags.fuel],
		Fuel : 5,
	},
	desertLog : {
		Name : "item_desert_log",
		Weight : 0.3,
		Item : obj_log,
		InvSprite : spr_desert_log,
		Flags : [flags.pickup, flags.remeltable, flags.fuel],
		Fuel : 7,
	},
	bed : {
		Name : "item_bed",
		Weight : 3,
		Item : obj_bed,
		InvSprite : spr_bed,
		Flags : [flags.interactive],
	},
	bedItem : {
		Name : "item_bed",
		Weight : 3,
		Item : obj_bed_item,
		InvSprite : spr_bed_mini,
		Flags : [flags.pickup, flags.placeble],
		Replaceble : obj_bed,
		ReplacebleSprite : spr_bed,
	},
	bonfire : {
		Name : "item_bonfire",
		Weight : 0.5,
		Item : obj_bonfire,
		InvSprite : spr_bonfire,
		Flags : [flags.interactive],
	},
	bonfireItem : {
		Name : "item_bonfire",
		Weight : 0.5,
		Item : obj_bonfire,
		InvSprite : spr_bonfire,
		Flags : [flags.pickup, flags.placeble, flags.remeltable, flags.fuel],
		Replaceble : obj_bonfire,
		ReplacebleSprite : spr_bonfire,
		Fuel : 3,
	},
	bake : {
		Name : "item_bake",
		Weight : 2,
		Item : obj_bake,
		InvSprite : spr_bake_icon,
		Flags : [flags.pickup, flags.placeble, flags.interactive],
		Replaceble : obj_bake,
		ReplacebleSprite : spr_bake,
	},
	coal : {
		Name : "item_coal",
		Weight : 0.25,
		Item : obj_coal,
		InvSprite : spr_coal,
		Flags : [flags.pickup, flags.remeltable, flags.fuel],
		Fuel : 10,
	},
	ironIngot : {
		Name : "item_iron_ingot",
		Weight : 0.5,
		Item : obj_iron_ingot,
		InvSprite : spr_iron_ingot,
		Flags : [flags.pickup],
	},
	ironOre : {
		Name : "item_iron_ore",
		Weight : 0.5,
		Item : obj_iron_ore,
		InvSprite : spr_iron_ore,
		Flags : [flags.pickup, flags.remeltable],
		MeltDef : 30,
		MeltRes : obj_iron_ingot,
	},
	goldIngot : {
		Name : "item_gold_ingot",
		Weight : 0.8,
		Item : obj_gold_ingot,
		InvSprite : spr_gold_ingot,
		Flags : [flags.pickup],
	},
	goldOre : {
		Name : "item_gold_ore",
		Weight : 1,
		Item : obj_gold_ore,
		InvSprite : spr_gold_ore,
		Flags : [flags.pickup, flags.remeltable],
		MeltDef : 60,
		MeltRes : obj_gold_ingot,
	},
	glass : {
		Name : "item_glass",
		Weight : 0.4,
		Item : obj_glass,
		InvSprite : spr_glass,
		Flags : [flags.pickup],
	},
	testTube : {
		Name : "item_test_tube",
		Weight : 0.1,
		Item : obj_test_tube,
		InvSprite : spr_test_tube,
		Flags : [flags.pickup],
	},
	testTubeWithMana : {
		Name : "item_test_tube_with_mana",
		Weight : 0.2,
		Item : obj_test_tube_with_mana,
		InvSprite : spr_test_tube_with_mana,
		Flags : [flags.pickup, flags.food],
		Food : [food_stats.mn, 30],
	},
	testTubeWithHealth : {
		Name : "item_test_tube_with_health",
		Weight : 0.2,
		Item : obj_test_tube_with_health,
		InvSprite : spr_test_tube_with_health,
		Flags : [flags.pickup, flags.food],
		Food : [food_stats.hp, 50],
	},
	testTubeWithEssenceOfNight : {
		Name : "item_test_tube_with_essence_of_night",
		Weight : 0.2,
		Item : obj_test_tube_with_essence_of_night,
		InvSprite : spr_test_tube_with_essence_of_night,
		Flags : [flags.pickup],
	},
	testTubeWithEssenceOfDay : {
		Name : "item_test_tube_with_essence_of_day",
		Weight : 0.05,
		Item : obj_test_tube_with_essence_of_day,
		InvSprite : spr_test_tube_with_essence_of_day,
		Flags : [flags.pickup],
	},
	hearthFlowerSeed : {
		Name : "item_hearth_flower_seed",
		Weight : 0.01,
		Item : obj_hearth_flower_seed,
		InvSprite : spr_hearth_flower_seed,
		Flags : [flags.pickup, flags.placeble, flags.remeltable, flags.fuel],
		Replaceble : obj_hearth_flower,
		ReplacebleSprite : spr_hearth_flower,
		Fuel : 1,
	},
	manaFlowerSeed : {
		Name : "item_mana_flower_seed",
		Weight : 0.005,
		Item : obj_mana_flower_seed,
		InvSprite : spr_mana_flower_seed,
		Flags : [flags.pickup, flags.placeble, flags.remeltable, flags.fuel],
		Replaceble : obj_mana_flower,
		ReplacebleSprite : spr_mana_flower,
		Fuel : 1,
	},
	hearthFlowerFruit : {
		Name : "item_hearth_flower",
		Weight : 0.1,
		Item : obj_hearth_flower_fruit,
		InvSprite : spr_hearth_flower_fruit,
		Flags : [flags.pickup, flags.food, flags.remeltable, flags.fuel],
		Food : [food_stats.hp, 10],
		Fuel : 1,
	},
	manaFlowerFruit : {
		Name : "item_mana_flower",
		Weight : 0.05,
		Item : obj_mana_flower_fruit,
		InvSprite : spr_mana_flower_fruit,
		Flags : [flags.pickup, flags.food, flags.remeltable, flags.fuel],
		Food : [food_stats.mn, 10],
		Fuel : 1,
	},
	evilEye : {
		Name : "item_evil_eye",
		Weight : 0.05,
		Item : obj_evil_eye_item,
		InvSprite : spr_evil_eye_item,
		Flags : [flags.pickup, flags.food],
		Food : [food_stats.mn, 5, food_stats.hp, 5],
		Fuel : 1,
	},
	thornBerry : {
		Name : "item_thorn_berry",
		Weight : 0.1,
		Item : obj_thorn_berry,
		InvSprite : spr_thorn_herry,
		Flags : [flags.pickup, flags.food],
		Food : [food_stats.hp, 15],
		Fuel : 2,
	},
	grassTile : {
		Name : "item_grass",
		Weight : 0.1,
		Item : obj_grass_tile,
		InvSprite : spr_grass_tile,
		Flags : [flags.pickup, flags.remeltable, flags.fuel],
		Fuel : 1,
	},
	stoneTile : {
		Name : "item_stone",
		Weight : 0.3,
		Item : obj_stone_tile,
		InvSprite : spr_stone_tile,
		Flags : [flags.pickup],
	},
	sandTile : {
		Name : "item_sand",
		Weight : 0.05,
		Item : obj_sand_tile,
		InvSprite : spr_sand_tile,
		Flags : [flags.pickup, flags.remeltable],
		MeltDef : 5,
		MeltRes : ObGlass,
	},
	ironHelmet : {
		Name : "item_iron_helmet",
		Weight : 1,
		Item : obj_iron_helmet,
		InvSprite : spr_iron_helmet,
		Flags : [flags.pickup, flags.armor, flags.head],
		Protection : 1,
	},
	ironChestplate : {
		Name : "item_iron_chestplate",
		Weight : 2,
		Item : obj_iron_chestplate,
		InvSprite : spr_iron_chestplate,
		Flags : [flags.pickup, flags.armor, flags.body],
		Protection : 2,
	},
	ironLeggins : {
		Name : "item_iron_leggins",
		Weight : 1,
		Item : obj_iron_leggins,
		InvSprite : spr_iron_leggins,
		Flags : [flags.pickup, flags.armor, flags.leggins],
		Protection : 1,
	},
	ironBoots : {
		Name : "item_iron_boots",
		Weight : 0.5,
		Item : obj_iron_boots,
		InvSprite : spr_iron_boots,
		Flags : [flags.pickup, flags.armor, flags.boots],
		Protection : 1,
	},
	goldHelmet : {
		Name : "item_gold_helmet",
		Weight : 2,
		Item : obj_gold_helmet,
		InvSprite : spr_gold_helmet,
		Flags : [flags.pickup, flags.armor, flags.head],
		Protection : 1,
	},
	goldChestplate : {
		Name : "item_gold_chestplate",
		Weight : 3,
		Item : obj_gold_chestplate,
		InvSprite : spr_gold_chestplate,
		Flags : [flags.pickup, flags.armor, flags.body],
		Protection : 3,
	},
	goldLeggins : {
		Name : "item_gold_leggins",
		Weight : 2,
		Item : obj_gold_leggins,
		InvSprite : spr_gold_leggins,
		Flags : [flags.pickup, flags.armor, flags.leggins],
		Protection : 2,
	},
	goldBoots : {
		Name : "item_gold_boots",
		Weight : 1.5,
		Item : obj_gold_boots,
		InvSprite : spr_gold_boots,
		Flags : [flags.pickup, flags.armor, flags.boots],
		Protection : 1,
	},
	echo : {
		Name : "item_echo",
		Weight : 0.01,
		Item : obj_echo,
		InvSprite : spr_echo,
		Flags : [flags.pickup],
	},
	slime : {
		Name : "item_slime",
		Weight : 0.01,
		Item : obj_item_slime,
		InvSprite : spr_item_slime,
		Flags : [flags.pickup, flags.fuel],
		Fuel: 2,
	},
	essenceOfNight : {
		Name : "item_essence_of_night",
		Weight : 0.5,
		Item : obj_essence_of_night,
		InvSprite : spr_essence_of_night,
		Flags : [flags.pickup],
	},
	essenceOfDay : {
		Name : "item_essence_of_day",
		Weight : 0.3,
		Item : obj_essence_of_day,
		InvSprite : spr_essence_of_day,
		Flags : [flags.pickup],
	},
	treeSeed : {
		Name : "item_tree_seed",
		Weight : 0.005,
		Item : obj_tree_seed,
		InvSprite : spr_tree_seed,
		Flags : [flags.pickup, flags.placeble, flags.remeltable, flags.fuel],
		Replaceble : obj_tree_grow,
		ReplacebleSprite : spr_tree_grow,
		Fuel : 1,
	},
	manaRecoveryBracelet : {
		Name : "item_mana_recovery_bracelet",
		Weight : 1,
		Item : obj_mana_recovery_bracelet,
		InvSprite : spr_mana_recovery_bracelet,
		Flags : [flags.pickup, flags.armor, flags.body, flags.recover],
		Food : [food_stats.mn, 1],
		Protection : 1,
	},
	healthRecoveryBracelet : {
		Name : "item_health_recovery_bracelet",
		Weight : 1,
		Item : obj_health_recovery_bracelet,
		InvSprite : spr_health_recovery_bracelet,
		Flags : [flags.pickup, flags.armor, flags.body, flags.recover],
		Food : [food_stats.hp, 1],
		Protection : 1,
	},
	recoveryBracelet : {
		Name : "item_recovery_bracelet",
		Weight : 3,
		Item : obj_recovery_bracelet,
		InvSprite : spr_recovery_bracelet,
		Flags : [flags.pickup, flags.armor, flags.body, flags.recover],
		Food : [food_stats.hp, 1, food_stats.mn, 1],
		Protection : 2,
	},
	summonerMergedSlime : {
		Name : "item_summoner_merged_slime",
		Weight : 0.025,
		Item : obj_summoner_merged_slime,
		InvSprite : spr_summoner_merged_slime,
		Flags : [flags.pickup, flags.placeble],
		Replaceble : obj_boss_merged_slime,
		ReplacebleSprite : spr_void,
	},
}

/// @fucn item_find_flag(item, flag)
function item_find_flag(_item, _flag){
	if (!_item) { return false; }
	var _flags;
	
	if (!is_struct(_item)){
		if (!variable_instance_exists(_item, "item")) { return false; }
		
		_flags = _item.Item[$ "flags"];
	}else{
		_flags = _item[$ "flags"];
	}
	
	var _len = array_length(_flags);
	
	for(var i = 0; i < _len; i++){
		if (_flags[i] == _flag) { return true; }
	}
	
	return false;
}